/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mhH5srKVuz7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
"use client";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { login } from "@/app/auth/login/actions";
import Image  from "next/image";
import { Divide } from "lucide-react";

interface LoginFormProps {
  LoginEmail: (
    email: string,
    password: string,
  ) => Promise<void>;
  LoginGoogle: () => Promise<void>;
}

export function LoginShadcn({ LoginEmail, LoginGoogle }: LoginFormProps) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  

  return (
    <Card className="mx-auto max-w-sm mt-10">
      <CardHeader>
        <CardTitle className="text-2xl">Login</CardTitle>
        <CardDescription>
          Enter your email below to login to your account
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={async (e) => {
          e.preventDefault();
          await LoginEmail(email, password);
        }}>
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                placeholder="m@example.com"
                required
                type="email"
                onChange={(e) => setEmail(e.target.value)}
                value={email}
              />
            </div>
            <div className="grid gap-2">
              <div className="flex items-center">
                <Label htmlFor="password">Password</Label>
                <Link
                  className="ml-auto inline-block text-sm underline"
                  href="#"
                >
                  Forgot your password&lsquo;?
                </Link>
              </div>
              <Input
                id="password"
                required
                type="password"
                onChange={(e) => setPassword(e.target.value)}
                value={password}
              />
            </div>
            <Button className="w-full" type="submit">
              Login
            </Button>
          </div>
        
          </form>
          <div className="mt-4 text-center text-sm">
            Don&rsquo;t have an account?
            <Link className="underline" href="/auth/signup">
              Sign up
            </Link>
          </div>
            <div className="flex items-center justify-center">
            <button onClick={async () => {
              await LoginGoogle();
            }} className="mt-5 " >
              <Image src="/googleLogin.svg" alt="Google Logo" width={200} height={200} />
            </button>
            </div>
          
      </CardContent>
    </Card>
  )
}
